CREATE OR REPLACE PACKAGE CUSTOMER_PCKG IS
	TYPE NUM_ARR IS VARRAY(1000000000) OF NUMBER;
	
	PROCEDURE CHANGE_INTERNET_PACKAGE (
		IN_USERNAME IN VARCHAR2,
		IN_NEW_PACKAGE IN VARCHAR2
	);
	
	FUNCTION ORDERED_INVOICES (
		IN_USERNAME IN VARCHAR2
	) RETURN CUSTOMER_PCKG.NUM_ARR;
	
	PROCEDURE REQUEST_SERVICE (
		IN_USERNAME IN VARCHAR2,
		IN_DATE IN DATE,
		IN_DEPARTMENT IN VARCHAR2,
		IN_DETAILS IN VARCHAR2
	);
	
	FUNCTION LOGIN (
		IN_USERNAME IN VARCHAR2,
		IN_PASSWORD IN CHAR
	) RETURN VARCHAR;
	
	PROCEDURE CHANGE_PASSWORD (
		IN_USERNAME IN VARCHAR2,
		IN_NEW_PASSWORD IN CHAR
	);
END PACKAGE;